import {
  UtensilsCrossed,
  CookingPot,
  Soup,
  Package,
  BookOpen,
  Book,
  Library,
  Stethoscope,
  Syringe,
  Scissors,
  BriefcaseMedical,
  ClipboardList,
  Clipboard,
  Wrench,
  Hammer,
  Cog,
  Drill,
  Ruler,
  HardHat,
  Fuel,
  DraftingCompass,
  FlaskConical,
  Microscope,
  Notebook,
  NotebookPen,
  Glasses,
  Dna,
  Search,
  TestTubes,
  BarChart3,
  Flame,
  Thermometer,
  BatteryFull,
  Lightbulb,
  Calculator,
  Mouse,
  Clock,
  Flashlight,
  Laptop,
  Keyboard,
  FileCode,
  Coffee,
  Bug,
  Pen,
  Globe,
  ScrollText,
  Radio,
  Scale,
  Megaphone,
  Medal,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  "Oshpaz Pichog'i": UtensilsCrossed,
  "Qovurilgan Tovasi": CookingPot,
  "Aralashtirish Kosasi": Soup,
  "Ziravorlar Javoni": Package,
  "Retsept Kitobi": BookOpen,
  Olov: Flame,

  Stetoskop: Stethoscope,
  Shprits: Syringe,
  Skalpel: Scissors,
  "Birinchi Yordam Qutisi": BriefcaseMedical,
  "Tibbiy Jadval": ClipboardList,
  Termometr: Thermometer,

  "Gayka Kaliti": Wrench,
  Otvertka: Cog,
  "Bolg'a": Hammer,
  "Asboblar Qutisi": Package,
  "Moy Idishi": Fuel,
  Akkumulyator: BatteryFull,

  Drel: Drill,
  "O'lchov Lentasi": Ruler,
  Chizmalar: DraftingCompass,
  "Qattiq Dubulg'a": HardHat,
  Lampochka: Lightbulb,

  "Tadqiqot Daftari": NotebookPen,
  Mikroskop: Microscope,
  Lupa: Search,
  Probirka: TestTubes,
  "Statistik Jadval": BarChart3,
  Kalkulyator: Calculator,

  // Legacy (kept for safety if data is reused elsewhere)
  Stakanlar: FlaskConical,
  "Laboratoriya Daftari": Notebook,
  "Ko'zoynak": Glasses,
  "DNK Namunasi": Dna,

  Noutbuk: Laptop,
  Klaviatura: Keyboard,
  "Kod Muharriri": FileCode,
  Kofe: Coffee,
  "Debugging Asboblari": Bug,
  Sichqoncha: Mouse,

  Kitoblar: Library,
  "Doska Markeri": Pen,
  Darslik: Book,
  Globus: Globe,
  Sertifikat: ScrollText,
  Soat: Clock,

  "Radio Aloqa": Radio,
  "Huquq Kitobi": Scale,
  Daftar: Clipboard,
  Hushtак: Megaphone,
  Nishon: Medal,
  Chiroq: Flashlight,
};

export function InstrumentIcon({
  name,
  size = 56,
  className,
}: {
  name: string;
  size?: number;
  className?: string;
}) {
  const Icon = ICONS[name] ?? Package;
  return <Icon size={size} strokeWidth={1.5} className={className} />;
}
